version: "3.4"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/usr/src/marble
        environment:
            - PHP_IDE_CONFIG=serverName=docker
            - XDEBUG_MODE=develop,debug,coverage
            - XDEBUG_TRIGGER=1
            - XDEBUG_CONFIG=idekey=PHPSTORM
